notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
language: c
compiler:
  - gcc
addons:
  postgresql: "9.4"
sudo: required
# env:
#   - GROONGA_MASTER=yes
install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y postgresql-server-dev-9.4
before_script:
  - make DEBUG=1
  - sudo make install
script:
  - rm -rf sql/jsonb
  - make installcheck || (cat regression.diffs; false)
