notifications:
  email:
    recipients:
      - groonga-commit@lists.osdn.me
dist: trusty
language: c
matrix:
  include:
    - env: PG_VERSION=9.3
      addons:
        postgresql: "9.3"
    - env: PG_VERSION=9.4
      addons:
        postgresql: "9.4"
    - env: PG_VERSION=9.5
      addons:
        postgresql: "9.5"
    - env: PG_VERSION=9.6
      addons:
        postgresql: "9.6"
sudo: required
# env:
#   - GROONGA_MASTER=yes
install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y postgresql-server-dev-${PG_VERSION} libmsgpack-dev groonga-token-filter-stem
  - |
    if [ ${PG_VERSION} = "9.6" ]; then
      rvm use 2.3.3 --install --binary --fuzzy
      gem install test-unit
    fi
before_script:
  - PKG_CONFIG_PATH=$PWD/data/travis/pkgconfig make DEBUG=1 HAVE_MSGPACK=1
  - sudo make install
script:
  - |
    case ${PG_VERSION} in
      9.3)
        rm -rf sql/jsonb
        rm -rf sql/function/flush/jsonb.sql
        rm -rf sql/reindex/analyze.sql
        rm -rf sql/groonga-function/tuple-is-alive/
        rm -rf sql/groonga-function/tuple-is-alive/
        rm -rf sql/term-search/text/options/tokenizer/ignored.sql
        ;;
      9.4)
        rm -rf sql/term-search/text/options/tokenizer/ignored.sql
        ;;
    esac
  - sudo -u postgres -H mkdir -p /tmp/space
  - make installcheck TMP_DIR=/tmp SETUP_TMP_DIR=no
  - |
    if [ ${PG_VERSION} = "9.6" ]; then
      test/run-test.rb
    fi
after_failure:
  - cat regression.diffs
