notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
language: c
compiler:
  - gcc
  - clang
addons:
  postgresql: "9.4"
install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get install -qq -y postgresql-server-dev-all
before_script:
  - make DEBUG=1
  - sudo make install
script:
  - make installcheck
