notifications:
  email:
    recipients:
      - groonga-commit@lists.osdn.me
dist: trusty
language: c
matrix:
  include:
    - env: PG_VERSION=9.3
      addons:
        postgresql: "9.3"
    - env: PG_VERSION=9.4
      addons:
        postgresql: "9.4"
    - env: PG_VERSION=9.5
      addons:
        postgresql: "9.5"
    - env: PG_VERSION=9.6
      addons:
        postgresql: "9.6"
sudo: required
# env:
#   - GROONGA_MASTER=yes
install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y postgresql-server-dev-${PG_VERSION}
before_script:
  - make DEBUG=1
  - sudo make install
script:
  - |
    if [ ${PG_VERSION} = "9.3" ]; then
      rm -rf sql/jsonb
      rm -rf sql/function/flush/jsonb.sql
      rm -rf sql/reindex/analyze.sql
      rm -rf sql/groonga-function/tuple-is-alive/
    fi
  - sudo -u postgres -H mkdir -p /tmp/space
  - make installcheck TMP_DIR=/tmp SETUP_TMP_DIR=no
after_failure:
  - cat regression.diffs
