notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
dist: trusty
language: c
compiler:
  - gcc
matrix:
  include:
    - env: PG_VERSION=9.3
      addons:
        postgresql: "9.3"
    - env: PG_VERSION=9.4
      addons:
        postgresql: "9.4"
sudo: required
# env:
#   - GROONGA_MASTER=yes
install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y postgresql-server-dev-${PG_VERSION}
before_script:
  - make DEBUG=1
  - sudo make install
script:
  - rm -rf sql/jsonb
  - rm -rf sql/function/flush/jsonb.sql
  - make installcheck || (cat regression.diffs; false)
