version: "{build}"
clone_depth: 10
build_script:
  - git submodule update --init
  - cd ..
  - choco install -y curl 7zip.commandline
  - curl -O http://get.enterprisedb.com/postgresql/postgresql-9.5.2-1-windows-x64-binaries.zip
  - 7z x postgresql-9.5.2-1-windows-x64-binaries.zip > nul
  - cd pgroonga
  - curl -O http://packages.groonga.org/source/groonga/groonga-6.0.1.zip
  - 7z x groonga-6.0.1.zip > nul
  - mv groonga-6.0.1 vendor\groonga
  - cmake . -G "Visual Studio 12 2013 Win64"
      -DCMAKE_INSTALL_PREFIX="..\\pgsql"
      -DGRN_WITH_MRUBY=yes
      -DGRN_WITH_BUNDLED_MECAB=yes
      -DGRN_WITH_BUNDLED_LZ4=yes
  - cmake --build . --config Debug
  - cmake --build . --config Debug --target Install

notifications:
  - provider: Email
    to:
      - kou@clear-code.com
      - groonga-commit@lists.sourceforge.jp
    on_build_status_changed: true

test: off
# before_test:
#   - gem install grntest
# test_script:
#   - grntest --groonga src\groonga.exe --base-directory test\command test\command\suite
